### PR TITLE
Cache username lookups

### PR DESCRIPTION
**Pull request by PaulBGD**

### CODE REVIEW

**Comment by creatorfromhell** [comment]
Has this been tested?

**Comment by PaulBGD** [comment]
It hasn't, but logically it should be good. Given that offlineplayers can be cached anyways, the behavior of this doesn't change anything.

It also is a significant performance improvement to plugins which use non-existent users to store things (towny, factions, etc.)

**Comment by FixTheAdmin** [comment]
EarthMC is currently down because of an issue related to what this patch fixes. Looking forward to see it included in TNE. Thanks for the help Paul.

**Comment by 0xBit-MC** [comment]
> 
> 
> This is a really nice addition, actually something that has been needed to be added for a while. Has this been tested?

Testing this build ingame on EarthPol resulted in the following https://pastebin.com/raw/xCSwyzVY

All account balances returned $0.00

**Comment by creatorfromhell** [comment]
> > This is a really nice addition, actually something that has been needed to be added for a while. Has this been tested?
> 
> Testing this build ingame on EarthPol resulted in the following https://pastebin.com/raw/xCSwyzVY
> 
> All account balances returned $0.00

That's what I was getting testing this too

**Comment by creatorfromhell** [comment]
I merged this into the range-patch branch. Thanks for the contribution.

**Comment by FixTheAdmin** [comment]
Latest pre release contains a dupe glitch. t deposit and t withdraw quickly sometimes dupes currency. We also experienced ender chests clearing on purchase. Probably related to this this.

**Pull request closed without merging**
